services:
  metrics:
    build: .
    container_name: post_profile_metrics
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/post_profile_db
    depends_on:
      - database

  database:
    image: postgres:17
    container_name: post_profile_metric_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_profile_db
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  psql_data:
